In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data_train = pd.read_csv("trainn.csv")
data_train = data_train.iloc[:,1:]
data_train

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
0,6,0.120,52012,3389,88.0,3,217,43,2,139,...,2,0,4,2,0,2,0,66,66,0
1,6,1.239,9454,3389,88.0,9,1170,672,6,637,...,2,0,14,9,0,2,0,66,66,0
2,6,0.057,13910,3389,88.0,1,171,117,1,54,...,0,0,2,1,0,0,0,0,0,0
3,6,0.312,14708,3389,88.0,2,193,85,2,108,...,0,0,4,1,0,0,1,0,0,0
4,6,1.733,18056,3389,88.0,10,1225,673,8,745,...,2,0,17,9,0,2,1,66,66,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3763547,6,8.952,1231,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3763548,6,8.964,1229,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3763549,6,8.894,1227,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3763550,6,8.983,1245,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3763551,6,0.709,1539,80,7.0,9,1334,840,12,12991,...,0,0,20,5,0,2,2,62,62,5

In [3]:
data_test = pd.read_csv("test.csv")
data_test

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
0,6,0.773,55872,445,16.0,5,564,286,4,394,...,0,0,8,5,1,2,0,62,62,0
1,6,3.849,47036,3389,88.0,13,2173,1459,9,2229,...,2,0,21,12,0,2,1,66,66,0
2,6,2.919,35055,3389,88.0,11,2090,1484,9,2225,...,0,0,19,12,0,2,1,66,66,0
3,6,4.113,54399,3389,88.0,14,2228,1460,9,2229,...,2,0,22,12,0,2,1,66,66,0
4,6,2.057,49864,3389,88.0,9,2287,1789,8,2037,...,0,0,16,11,1,2,0,66,66,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269995,6,0.640,1398,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
269996,6,0.577,1364,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
269997,6,0.666,1366,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
269998,6,0.687,1461,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
269999,6,16.740,1374,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5

In [4]:
data_train = data_train.sample(n = 10000)
data_test = data_test.sample(n = 1000)

In [5]:
#Train-test split
from sklearn.model_selection import train_test_split
x = data_train.iloc[:,:-1]
y = data_train.iloc[:,-1:]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
X_train

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_cwr,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win
2614847,6,0.010,56536,22,92.7,6,640,236,7,524,...,0,0,0,11,4,2,2,0,74,74
3459829,6,2.629,49808,21,1.0,9,629,27,7,546,...,0,0,0,15,5,0,2,2,74,74
1004998,6,0.709,38790,445,16.0,5,655,373,4,400,...,0,0,0,8,5,1,2,0,66,66
2423485,6,0.155,57389,80,7.0,3,349,175,1,66,...,0,0,0,3,1,0,2,0,66,66
1047459,6,3.820,55585,3389,88.0,9,1646,1148,7,1971,...,0,2,0,15,10,1,2,0,66,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1013280,6,5.757,49311,80,7.0,5,379,97,4,459,...,0,2,0,8,2,0,2,1,66,66
872214,6,0.805,54223,445,16.0,5,564,286,4,394,...,0,0,0,8,5,1,2,0,62,62
2988120,17,2816.666,33490,22,0.0,636,47064,20352,0,0,...,0,0,0,0,0,0,0,0,0,0
2383010,6,0.813,64850,80,7.0,5,696,414,4,473,...,0,0,0,8,3,0,2,0,66,66
1784911,6,5.107,63044,3389,88.0,10,2385,1821,9,2103,...,0,4,0,17,11,1,4,0,66,66

In [6]:
X_test

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_cwr,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win
1732599,6,1.925,25707,3389,88.0,10,1228,676,8,745,...,0,2,0,17,9,0,2,1,66,66
1271209,6,2.042,57156,3389,88.0,8,1588,1148,7,1967,...,0,0,0,14,10,1,2,0,62,62
1012695,6,0.255,56080,445,41.0,3,170,0,3,166,...,0,0,0,5,0,1,2,1,62,58
3179215,17,1819.728,20622,22,0.0,33,2442,1056,0,0,...,0,0,0,0,0,0,0,0,0,0
1397015,6,1.976,49217,3389,88.0,9,1626,1128,7,1971,...,0,2,0,15,10,1,2,0,66,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13947,6,1.293,58919,3389,88.0,8,1592,1148,7,1971,...,0,2,0,14,10,1,2,0,66,66
118411,6,3.636,52146,3389,88.0,10,2019,1467,11,3443,...,0,0,0,20,14,1,2,0,66,66
2378935,6,0.016,65497,80,7.0,3,360,186,1,66,...,0,0,0,3,1,0,2,0,66,66
3478044,6,3.223,36974,21,1.0,9,628,26,7,546,...,0,0,0,15,5,0,2,2,74,74
1125233,6,2.847,26255,3389,88.0,14,2256,1488,9,2229,...,0,2,0,22,12,0,2,1,66,66

In [7]:
y_train

         NewLabel
2614847         2
3459829         4
1004998         0
2423485         1
1047459         0
...           ...
1013280         0
872214          0
2988120         3
2383010         1
1784911         0

[8000 rows x 1 columns]

In [8]:
y_test

         NewLabel
1732599         0
1271209         0
1012695         0
3179215         3
1397015         0
...           ...
13947           0
118411          0
2378935         1
3478044         4
1125233         0

[2000 rows x 1 columns]

In [9]:
# XGBoost Classification Feature Importance
from xgboost import XGBClassifier
from matplotlib import pyplot

model = XGBClassifier()
model.fit(X_train, y_train)
importance = model.feature_importances_

for i,v in enumerate(importance):
    print('Feature: %0d, Score: %.5f' % (i,v))

C:\Users\bengisu.kavurdu\Anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\bengisu.kavurdu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

[15:25:02] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Feature: 0, Score: 0.04765
Feature: 1, Score: 0.04354
Feature: 2, Score: 0.00548
Feature: 3, Score: 0.11917
Feature: 4, Score: 0.05236
Feature: 5, Score: 0.11943
Feature: 6, Score: 0.01717
Feature: 7, Score: 0.03623
Feature: 8, Score: 0.00635
Feature: 9, Score: 0.00648
Feature: 10, Score: 0.00322
Feature: 11, Score: 0.00466
Feature: 12, Score: 0.00438
Feature: 13, Score: 0.01165
Feature: 14, Score: 0.00244
Feature: 15, Score: 0.00537
Feature: 16, Score: 0.00363
Feature: 17, Score: 0.00234
Feature: 18, Score: 0.00651
Feature: 19, Score: 0.00581
Feature: 20, Score: 0.00219
Feature: 21, Score: 0.00420
Feature: 22, Score: 0.01512
Feature: 23, Score: 0.00269
Feature: 24, Score: 0.00619
Feature: 25, Score: 0.00213
Feature: 26, Score: 0.03032
Feature: 27, Score: 0.00428
Feature: 28, Score: 0.00723
Feature: 29, Score: 0.00322
Feature: 30, Score: 0.08821
Feature: 31, Score: 0.00578
Feature: 32, Score: 0.00627
Feature: 33, Score: 0.00364
Feature: 34, Score: 0.04087
Feature: 35, Score: 0.00057
Feature: 36, Score: 0.00000
Feature: 37, Score: 0.00525
Feature: 38, Score: 0.00943
Feature: 39, Score: 0.02962
Feature: 40, Score: 0.00178
Feature: 41, Score: 0.03272
Feature: 42, Score: 0.00547
Feature: 43, Score: 0.00022
Feature: 44, Score: 0.00000
Feature: 45, Score: 0.04781
Feature: 46, Score: 0.00679
Feature: 47, Score: 0.00856
Feature: 48, Score: 0.02951
Feature: 49, Score: 0.01018
Feature: 50, Score: 0.00000
Feature: 51, Score: 0.00000
Feature: 52, Score: 0.00000
Feature: 53, Score: 0.00000
Feature: 54, Score: 0.00000
Feature: 55, Score: 0.00000
Feature: 56, Score: 0.00000
Feature: 57, Score: 0.00000
Feature: 58, Score: 0.05701
Feature: 59, Score: 0.02888

In [10]:
def correlation(dataset,threshold):
    col_corr = set()
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i,j]) > threshold:
                colname = corr_matrix.columns[i]
                col_corr.add(colname)
    return col_corr

In [11]:
corr_features = correlation(X_train, 0.7)
len(set(corr_features))

36

In [12]:
X_train = X_train.drop(corr_features, axis = 1)
X_test = X_test.drop(corr_features, axis = 1)
X_train

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,s_to_c_pkts,s_to_c_bytes,data_ratio,c_to_s_goodput_ratio,...,iat_s_to_c_min,pktlen_c_to_s_min,pktlen_s_to_c_min,cwr,urg,rst,fin,c_to_s_urg,s_to_c_cwr,s_to_c_urg
2614847,6,0.010,56536,22,92.7,6,7,524,0.100,36.8,...,0,66,60,0,0,2,0,0,0,0
3459829,6,2.629,49808,21,1.0,9,7,546,0.071,4.3,...,0,66,66,0,0,0,2,0,0,0
1004998,6,0.709,38790,445,16.0,5,4,400,0.242,56.9,...,236,54,54,0,0,1,0,0,0,0
2423485,6,0.155,57389,80,7.0,3,1,66,0.682,50.0,...,0,54,66,0,0,0,0,0,0,0
1047459,6,3.820,55585,3389,88.0,9,7,1971,-0.090,69.7,...,213,54,54,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1013280,6,5.757,49311,80,7.0,5,4,459,-0.095,25.5,...,0,54,54,1,0,0,1,0,0,0
872214,6,0.805,54223,445,16.0,5,4,394,0.177,50.6,...,268,54,54,0,0,1,0,0,0,0
2988120,17,2816.666,33490,22,0.0,636,0,0,1.000,43.2,...,0,74,0,0,0,0,0,0,0,0
2383010,6,0.813,64850,80,7.0,5,4,473,0.191,59.4,...,0,54,60,0,0,0,0,0,0,0
1784911,6,5.107,63044,3389,88.0,10,9,2103,0.063,76.3,...,129,54,54,3,0,1,0,0,0,0

In [36]:
#Select top 15 features based on f_classif
from sklearn.feature_selection import SelectKBest, f_classif
selector = SelectKBest(f_classif, k = 15)
selector.fit(X_train, y_train)
rfbest15 = X_train.columns[selector.get_support()]

C:\Users\bengisu.kavurdu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

In [37]:
X_train.drop(X_train.columns.difference(rfbest15), 1, inplace=True)
X_train

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,data_ratio,c_to_s_goodput_ratio,s_to_c_goodput_ratio,iat_flow_avg,iat_flow_max,pktlen_c_to_s_min,pktlen_s_to_c_min,cwr,rst
2614847,6,0.010,56536,22,92.7,6,0.100,36.8,11.4,4.0,7,66,60,0,2
3459829,6,2.629,49808,21,1.0,9,0.071,4.3,13.9,1292.5,2583,66,66,0,0
1004998,6,0.709,38790,445,16.0,5,0.242,56.9,42.9,235.0,235,54,54,0,1
2423485,6,0.155,57389,80,7.0,3,0.682,50.0,0.0,153.0,153,54,66,0,0
1047459,6,3.820,55585,3389,88.0,9,-0.090,69.7,80.2,324.3,1228,54,54,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1013280,6,5.757,49311,80,7.0,5,-0.095,25.5,50.2,1918.7,5731,54,54,1,0
872214,6,0.805,54223,445,16.0,5,0.177,50.6,43.0,267.3,268,54,54,0,1
2988120,17,2816.666,33490,22,0.0,636,1.000,43.2,0.0,4674.5,117782,74,0,0,0
2383010,6,0.813,64850,80,7.0,5,0.191,59.4,49.2,202.8,525,54,60,0,0
1784911,6,5.107,63044,3389,88.0,10,0.063,76.3,75.1,392.2,3015,54,54,3,1

In [38]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1, metric='minkowski')
knn.fit(X_train,y_train)

C:\Users\bengisu.kavurdu\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=1)

In [39]:
X_test = data_test.iloc[:,:-1]
y_test = data_test.iloc[:,-1:]

In [41]:
X_test.drop(X_test.columns.difference(rfbest15), 1, inplace=True)
X_test

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,data_ratio,c_to_s_goodput_ratio,s_to_c_goodput_ratio,iat_flow_avg,iat_flow_max,pktlen_c_to_s_min,pktlen_s_to_c_min,cwr,rst
177835,17,5247.559,12563,22,0.0,1437,1.000,43.2,0.0,3892.1,135224,74,0,0,0
88041,6,0.173,63492,80,7.0,3,0.700,50.3,0.0,172.0,172,54,62,0,0
46551,6,0.045,56144,80,7.0,4,0.553,64.6,0.0,22.0,22,54,60,0,0
118538,6,2.690,47066,3389,88.0,8,-0.108,72.0,80.2,268.3,954,54,54,1,1
22981,6,2.529,11711,3389,88.0,12,-0.027,68.7,77.6,166.7,951,54,54,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124431,6,455.200,80,33642,7.0,7,0.564,79.9,48.1,91032.0,455071,66,66,0,0
257553,6,0.423,49196,80,7.0,5,0.221,51.2,38.8,84.0,155,60,60,0,0
188746,6,3.751,54800,21,1.0,9,0.071,4.3,13.9,1853.0,3704,66,66,0,0
171738,17,3729.585,34026,22,0.0,1045,1.000,43.2,0.0,3736.5,95284,74,0,0,0
75260,6,0.279,50869,80,7.0,4,0.480,56.9,0.0,138.5,139,54,60,0,0

In [42]:
X_train.shape

(8000, 15)

In [43]:
X_test.shape

(1000, 15)

In [44]:
y_train.shape

(8000, 1)

In [45]:
y_test.shape

(1000, 1)

In [46]:
y_pred = knn.predict(X_test)
print(y_test)
y_pred = pd.DataFrame(data = y_pred, columns = ['NewLabel'])
print(y_pred)

        NewLabel
177835         3
88041          1
46551          1
118538         2
22981          0
...          ...
124431         2
257553         5
188746         4
171738         3
75260          1

[1000 rows x 1 columns]
     NewLabel
0           3
1           1
2           4
3           0
4           0
..        ...
995         3
996         0
997         1
998         3
999         4

[1000 rows x 1 columns]

In [47]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
#711 True 289 False %71.1 true

[[152   0   0   0   0   1]
 [  8  88   0  14  75   0]
 [ 45   8  61  24  28   0]
 [  0   0   1 174   0   0]
 [  7   9   2   1 145   1]
 [ 38   7   7   6   7  91]]