In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv("4m_61f_all.csv")
data

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
0,17,0.000,780,44194,0.0,60,28920,26400,0,0,...,0,0,0,0,0,0,0,0,0,DDOS
1,17,0.001,863,45655,0.0,10,4820,4400,0,0,...,0,0,0,0,0,0,0,0,0,DDOS
2,17,0.002,863,45655,0.0,10,4820,4400,0,0,...,0,0,0,0,0,0,0,0,0,DDOS
3,17,0.000,941,46739,0.0,4,1928,1760,0,0,...,0,0,0,0,0,0,0,0,0,DDOS
4,17,0.001,941,46739,0.0,4,1928,1760,0,0,...,0,0,0,0,0,0,0,0,0,DDOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4033547,6,2.109,64083,3389,88.0,8,1588,1144,7,1971,...,0,0,14,10,1,2,0,66,66,Normal
4033548,6,1.880,21303,3389,88.0,9,1646,1148,7,1971,...,2,0,15,10,1,2,0,66,66,Normal
4033549,6,1.779,56493,3389,88.0,9,1646,1148,7,1971,...,2,0,15,10,1,2,0,66,66,Normal
4033550,6,60.647,49707,443,91.0,14,1534,766,14,4678,...,1,0,27,7,0,2,2,66,58,Normal
4033551,6,9.035,49712,443,91.0,3,194,0,0,0,...,2,0,0,0,0,3,0,66,0,Normal

In [3]:
x = data["NewLabel"].value_counts()
print(x)

Normal            2403724
DDOS               611405
BruteForce         475321
Infiltration       268064
DoS                183477
MalwareActivty      91561
Name: NewLabel, dtype: int64

In [4]:
newLabel = data.iloc[:, -1:]
newLabel

        NewLabel
0           DDOS
1           DDOS
2           DDOS
3           DDOS
4           DDOS
...          ...
4033547   Normal
4033548   Normal
4033549   Normal
4033550   Normal
4033551   Normal

[4033552 rows x 1 columns]

In [5]:
import category_encoders as ce
encoder= ce.OrdinalEncoder(cols=['NewLabel'],return_df=True, mapping=[{'col':'NewLabel','mapping':{'Normal':0,'Infiltration':1,'DoS':2,'DDOS':3,'BruteForce':4,'MalwareActivty':5}}])
df_train_transformed = encoder.fit_transform(newLabel)
encoderLabel = df_train_transformed
encoderLabel

C:\Users\bengisu.kavurdu\Anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

         NewLabel
0               3
1               3
2               3
3               3
4               3
...           ...
4033547         0
4033548         0
4033549         0
4033550         0
4033551         0

[4033552 rows x 1 columns]

In [6]:
encode_data = pd.concat([data.iloc[:, :-1],encoderLabel], axis=1)
encode_data

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
0,17,0.000,780,44194,0.0,60,28920,26400,0,0,...,0,0,0,0,0,0,0,0,0,3
1,17,0.001,863,45655,0.0,10,4820,4400,0,0,...,0,0,0,0,0,0,0,0,0,3
2,17,0.002,863,45655,0.0,10,4820,4400,0,0,...,0,0,0,0,0,0,0,0,0,3
3,17,0.000,941,46739,0.0,4,1928,1760,0,0,...,0,0,0,0,0,0,0,0,0,3
4,17,0.001,941,46739,0.0,4,1928,1760,0,0,...,0,0,0,0,0,0,0,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4033547,6,2.109,64083,3389,88.0,8,1588,1144,7,1971,...,0,0,14,10,1,2,0,66,66,0
4033548,6,1.880,21303,3389,88.0,9,1646,1148,7,1971,...,2,0,15,10,1,2,0,66,66,0
4033549,6,1.779,56493,3389,88.0,9,1646,1148,7,1971,...,2,0,15,10,1,2,0,66,66,0
4033550,6,60.647,49707,443,91.0,14,1534,766,14,4678,...,1,0,27,7,0,2,2,66,58,0
4033551,6,9.035,49712,443,91.0,3,194,0,0,0,...,2,0,0,0,0,3,0,66,0,0

In [7]:
sort_data = encode_data.sort_values(by=['NewLabel'])

In [8]:
sort_data.reset_index(inplace=True)
sort_data

,index,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
0,2016775,6,0.773,55872,445,16.0,5,564,286,4,...,0,0,8,5,1,2,0,62,62,0
1,2689027,6,3.849,47036,3389,88.0,13,2173,1459,9,...,2,0,21,12,0,2,1,66,66,0
2,2689028,6,2.919,35055,3389,88.0,11,2090,1484,9,...,0,0,19,12,0,2,1,66,66,0
3,2689029,6,4.113,54399,3389,88.0,14,2228,1460,9,...,2,0,22,12,0,2,1,66,66,0
4,2689030,6,2.057,49864,3389,88.0,9,2287,1789,8,...,0,0,16,11,1,2,0,66,66,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4033547,882836,6,0.577,1364,80,7.0,4,224,0,3,...,0,0,6,1,0,2,2,62,60,5
4033548,882837,6,0.666,1366,80,7.0,4,224,0,3,...,0,0,6,1,0,2,2,62,60,5
4033549,882838,6,0.687,1461,80,7.0,4,224,0,3,...,0,0,6,1,0,2,2,62,60,5
4033550,882818,6,16.740,1374,80,7.0,4,224,0,3,...,0,0,6,1,0,2,2,62,60,5
4033551,858838,6,0.709,1539,80,7.0,9,1334,840,12,...,0,0,20,5,0,2,2,62,62,5

In [9]:
new_data = sort_data.iloc[:, 1:]
new_data

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
0,6,0.773,55872,445,16.0,5,564,286,4,394,...,0,0,8,5,1,2,0,62,62,0
1,6,3.849,47036,3389,88.0,13,2173,1459,9,2229,...,2,0,21,12,0,2,1,66,66,0
2,6,2.919,35055,3389,88.0,11,2090,1484,9,2225,...,0,0,19,12,0,2,1,66,66,0
3,6,4.113,54399,3389,88.0,14,2228,1460,9,2229,...,2,0,22,12,0,2,1,66,66,0
4,6,2.057,49864,3389,88.0,9,2287,1789,8,2037,...,0,0,16,11,1,2,0,66,66,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4033547,6,0.577,1364,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033548,6,0.666,1366,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033549,6,0.687,1461,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033550,6,16.740,1374,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033551,6,0.709,1539,80,7.0,9,1334,840,12,12991,...,0,0,20,5,0,2,2,62,62,5

In [10]:
normal = new_data.iloc[0:45000]
normal

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
0,6,0.773,55872,445,16.0,5,564,286,4,394,...,0,0,8,5,1,2,0,62,62,0
1,6,3.849,47036,3389,88.0,13,2173,1459,9,2229,...,2,0,21,12,0,2,1,66,66,0
2,6,2.919,35055,3389,88.0,11,2090,1484,9,2225,...,0,0,19,12,0,2,1,66,66,0
3,6,4.113,54399,3389,88.0,14,2228,1460,9,2229,...,2,0,22,12,0,2,1,66,66,0
4,6,2.057,49864,3389,88.0,9,2287,1789,8,2037,...,0,0,16,11,1,2,0,66,66,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,6,2.037,53595,3389,88.0,5,441,159,4,247,...,2,0,8,3,0,2,1,66,66,0
44996,6,1.493,39434,3389,88.0,6,1299,975,5,355,...,0,0,11,4,0,0,1,0,0,0
44997,6,0.304,41561,445,41.0,3,262,88,2,251,...,0,0,4,2,0,2,0,66,66,0
44998,6,0.294,50942,3389,91.0,3,317,155,1,1233,...,0,0,4,2,0,0,0,0,0,0
44999,6,1.906,3380,3389,88.0,10,1225,673,8,745,...,2,0,17,9,0,2,1,66,66,0

In [11]:
new_data = new_data.drop(new_data.index[0:45000])
new_data

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
45000,6,0.120,52012,3389,88.0,3,217,43,2,139,...,2,0,4,2,0,2,0,66,66,0
45001,6,1.239,9454,3389,88.0,9,1170,672,6,637,...,2,0,14,9,0,2,0,66,66,0
45002,6,0.057,13910,3389,88.0,1,171,117,1,54,...,0,0,2,1,0,0,0,0,0,0
45003,6,0.312,14708,3389,88.0,2,193,85,2,108,...,0,0,4,1,0,0,1,0,0,0
45004,6,1.733,18056,3389,88.0,10,1225,673,8,745,...,2,0,17,9,0,2,1,66,66,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4033547,6,0.577,1364,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033548,6,0.666,1366,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033549,6,0.687,1461,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033550,6,16.740,1374,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033551,6,0.709,1539,80,7.0,9,1334,840,12,12991,...,0,0,20,5,0,2,2,62,62,5

In [12]:
infiltration = new_data.iloc[2403724:2448724]
infiltration

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
2448724,6,0.281,53042,80,7.0,4,653,425,3,186,...,0,0,6,2,0,2,0,66,66,1
2448725,6,0.349,53043,80,7.0,4,676,448,3,186,...,0,0,6,2,0,2,0,66,66,1
2448726,6,1.818,52979,80,7.0,8,1398,954,7,1626,...,0,0,14,8,0,2,0,66,66,1
2448727,6,0.635,52957,80,7.0,5,632,350,3,589,...,0,0,7,3,0,2,0,66,62,1
2448728,6,0.288,80,52958,7.0,3,186,0,3,504,...,0,0,6,2,0,1,0,66,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2493719,6,0.048,56987,80,7.0,4,642,414,3,186,...,0,0,6,2,0,2,0,66,66,1
2493720,6,0.274,56988,80,7.0,3,353,179,3,703,...,0,0,5,2,0,2,0,66,66,1
2493721,6,0.317,56985,80,7.0,5,936,654,2,132,...,0,0,6,3,0,2,0,66,66,1
2493722,6,0.022,56992,80,7.0,4,664,436,3,186,...,0,0,6,2,0,2,0,66,66,1
2493723,6,0.319,56920,80,7.0,5,893,611,4,669,...,0,0,8,4,0,2,0,66,66,1

In [13]:
new_data = new_data.drop(new_data.index[2403724:2448724])
new_data

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
45000,6,0.120,52012,3389,88.0,3,217,43,2,139,...,2,0,4,2,0,2,0,66,66,0
45001,6,1.239,9454,3389,88.0,9,1170,672,6,637,...,2,0,14,9,0,2,0,66,66,0
45002,6,0.057,13910,3389,88.0,1,171,117,1,54,...,0,0,2,1,0,0,0,0,0,0
45003,6,0.312,14708,3389,88.0,2,193,85,2,108,...,0,0,4,1,0,0,1,0,0,0
45004,6,1.733,18056,3389,88.0,10,1225,673,8,745,...,2,0,17,9,0,2,1,66,66,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4033547,6,0.577,1364,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033548,6,0.666,1366,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033549,6,0.687,1461,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033550,6,16.740,1374,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033551,6,0.709,1539,80,7.0,9,1334,840,12,12991,...,0,0,20,5,0,2,2,62,62,5

In [14]:
DoS = new_data.iloc[2671788:2716788]
DoS

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
2761788,6,7.074,43038,80,7.0,5,649,311,3,1178,...,0,0,7,2,1,2,0,74,74,2
2761789,6,7.060,42986,80,7.0,5,715,377,3,868,...,0,0,7,2,1,2,0,74,74,2
2761790,6,7.026,42990,80,7.0,5,751,413,3,868,...,0,0,7,2,1,2,0,74,74,2
2761791,6,7.017,43034,80,7.0,5,831,493,3,1178,...,0,0,7,2,1,2,0,74,74,2
2761792,6,7.050,43032,80,7.0,5,907,569,3,1178,...,0,0,7,2,1,2,0,74,74,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2806783,17,6605.131,12925,21,0.0,19,1406,608,0,0,...,0,0,0,0,0,0,0,0,0,2
2806784,17,7071.812,12927,21,0.0,12,888,384,0,0,...,0,0,0,0,0,0,0,0,0,2
2806785,17,5818.547,12931,21,0.0,8,592,256,0,0,...,0,0,0,0,0,0,0,0,0,2
2806786,17,6405.108,12937,21,0.0,7,518,224,0,0,...,0,0,0,0,0,0,0,0,0,2
2806787,17,5352.174,12935,21,0.0,12,888,384,0,0,...,0,0,0,0,0,0,0,0,0,2

In [15]:
new_data = new_data.drop(new_data.index[2671788:2716788])
new_data

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
45000,6,0.120,52012,3389,88.0,3,217,43,2,139,...,2,0,4,2,0,2,0,66,66,0
45001,6,1.239,9454,3389,88.0,9,1170,672,6,637,...,2,0,14,9,0,2,0,66,66,0
45002,6,0.057,13910,3389,88.0,1,171,117,1,54,...,0,0,2,1,0,0,0,0,0,0
45003,6,0.312,14708,3389,88.0,2,193,85,2,108,...,0,0,4,1,0,0,1,0,0,0
45004,6,1.733,18056,3389,88.0,10,1225,673,8,745,...,2,0,17,9,0,2,1,66,66,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4033547,6,0.577,1364,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033548,6,0.666,1366,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033549,6,0.687,1461,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033550,6,16.740,1374,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033551,6,0.709,1539,80,7.0,9,1334,840,12,12991,...,0,0,20,5,0,2,2,62,62,5

In [16]:
DDOS = new_data.iloc[2855265:2900265]
new_data = new_data.drop(new_data.index[2855265:2900265])
DDOS

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
2990265,17,382.774,28322,22,0.0,20,1480,640,0,0,...,0,0,0,0,0,0,0,0,0,3
2990266,17,625.174,28336,22,0.0,14,1036,448,0,0,...,0,0,0,0,0,0,0,0,0,3
2990267,17,190.114,28784,22,0.0,23,1702,736,0,0,...,0,0,0,0,0,0,0,0,0,3
2990268,17,1320.418,28884,22,0.0,44,3256,1408,0,0,...,0,0,0,0,0,0,0,0,0,3
2990269,17,876.007,28840,22,0.0,41,3034,1312,0,0,...,0,0,0,0,0,0,0,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3035260,17,58914.418,13771,22,0.0,11840,876160,378880,0,0,...,0,0,0,0,0,0,0,0,0,3
3035261,17,6126.809,13941,22,0.0,1697,125578,54304,0,0,...,0,0,0,0,0,0,0,0,0,3
3035262,17,60829.145,14027,22,0.0,12384,916416,396288,0,0,...,0,0,0,0,0,0,0,0,0,3
3035263,17,65210.785,14263,22,0.0,13685,1012690,437920,0,0,...,0,0,0,0,0,0,0,0,0,3
3035264,17,29350.236,14423,22,0.0,3847,284678,123104,0,0,...,0,0,0,0,0,0,0,0,0,3

In [17]:
brute = new_data.iloc[3466670:3511670]
new_data = new_data.drop(new_data.index[3466670:3511670])
brute

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
3646670,6,6.579,34342,22,92.0,22,3208,1748,23,4563,...,0,0,44,26,0,2,2,74,74,4
3646671,6,3.226,42210,21,1.0,9,629,27,7,546,...,0,0,15,5,0,2,2,74,74,4
3646672,6,5.908,34336,22,92.0,15,2282,1284,20,3169,...,0,0,31,17,3,2,2,74,74,4
3646673,6,2.865,42202,21,1.0,9,629,27,8,612,...,0,0,16,5,0,2,3,74,74,4
3646674,6,5.769,34330,22,92.0,22,3208,1748,25,4659,...,0,0,43,26,3,2,2,74,74,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3691665,6,3.326,42384,21,1.0,9,628,26,7,546,...,0,0,15,5,0,2,2,74,74,4
3691666,6,2.242,42382,21,1.0,9,628,26,7,546,...,0,0,15,5,0,2,2,74,74,4
3691667,6,3.502,42380,21,1.0,9,628,26,7,546,...,0,0,15,5,0,2,2,74,74,4
3691668,6,3.085,42378,21,1.0,9,628,26,7,546,...,0,0,15,5,0,2,2,74,74,4
3691669,6,2.782,42374,21,1.0,9,628,26,7,546,...,0,0,15,5,0,2,2,74,74,4

In [18]:
new_data

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
45000,6,0.120,52012,3389,88.0,3,217,43,2,139,...,2,0,4,2,0,2,0,66,66,0
45001,6,1.239,9454,3389,88.0,9,1170,672,6,637,...,2,0,14,9,0,2,0,66,66,0
45002,6,0.057,13910,3389,88.0,1,171,117,1,54,...,0,0,2,1,0,0,0,0,0,0
45003,6,0.312,14708,3389,88.0,2,193,85,2,108,...,0,0,4,1,0,0,1,0,0,0
45004,6,1.733,18056,3389,88.0,10,1225,673,8,745,...,2,0,17,9,0,2,1,66,66,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4033547,6,0.577,1364,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033548,6,0.666,1366,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033549,6,0.687,1461,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033550,6,16.740,1374,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
4033551,6,0.709,1539,80,7.0,9,1334,840,12,12991,...,0,0,20,5,0,2,2,62,62,5

In [19]:
new_data.reset_index(inplace=True)

In [20]:
new_data.drop("index",inplace=True,axis=1)

In [21]:
new_data

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
0,6,0.120,52012,3389,88.0,3,217,43,2,139,...,2,0,4,2,0,2,0,66,66,0
1,6,1.239,9454,3389,88.0,9,1170,672,6,637,...,2,0,14,9,0,2,0,66,66,0
2,6,0.057,13910,3389,88.0,1,171,117,1,54,...,0,0,2,1,0,0,0,0,0,0
3,6,0.312,14708,3389,88.0,2,193,85,2,108,...,0,0,4,1,0,0,1,0,0,0
4,6,1.733,18056,3389,88.0,10,1225,673,8,745,...,2,0,17,9,0,2,1,66,66,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3808547,6,0.577,1364,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
3808548,6,0.666,1366,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
3808549,6,0.687,1461,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
3808550,6,16.740,1374,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
3808551,6,0.709,1539,80,7.0,9,1334,840,12,12991,...,0,0,20,5,0,2,2,62,62,5

In [22]:
malwareActivity = new_data.iloc[3763551:3808551]
new_data = new_data.drop(new_data.index[3763551:3808551])
malwareActivity

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
3763551,6,8.868,1208,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3763552,6,8.861,1210,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3763553,6,8.882,1212,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3763554,6,8.922,1260,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3763555,6,8.874,1256,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3808546,6,0.640,1398,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
3808547,6,0.577,1364,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
3808548,6,0.666,1366,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
3808549,6,0.687,1461,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
3808550,6,16.740,1374,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5

In [23]:
new_data

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
0,6,0.120,52012,3389,88.0,3,217,43,2,139,...,2,0,4,2,0,2,0,66,66,0
1,6,1.239,9454,3389,88.0,9,1170,672,6,637,...,2,0,14,9,0,2,0,66,66,0
2,6,0.057,13910,3389,88.0,1,171,117,1,54,...,0,0,2,1,0,0,0,0,0,0
3,6,0.312,14708,3389,88.0,2,193,85,2,108,...,0,0,4,1,0,0,1,0,0,0
4,6,1.733,18056,3389,88.0,10,1225,673,8,745,...,2,0,17,9,0,2,1,66,66,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3763547,6,8.952,1231,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3763548,6,8.964,1229,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3763549,6,8.894,1227,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3763550,6,8.983,1245,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3808551,6,0.709,1539,80,7.0,9,1334,840,12,12991,...,0,0,20,5,0,2,2,62,62,5

In [34]:
test = pd.concat([normal,infiltration,DoS,DDOS,brute,malwareActivity])
test.reset_index(inplace=True)
test = test.iloc[:,1:]
test

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
0,6,0.773,55872,445,16.0,5,564,286,4,394,...,0,0,8,5,1,2,0,62,62,0
1,6,3.849,47036,3389,88.0,13,2173,1459,9,2229,...,2,0,21,12,0,2,1,66,66,0
2,6,2.919,35055,3389,88.0,11,2090,1484,9,2225,...,0,0,19,12,0,2,1,66,66,0
3,6,4.113,54399,3389,88.0,14,2228,1460,9,2229,...,2,0,22,12,0,2,1,66,66,0
4,6,2.057,49864,3389,88.0,9,2287,1789,8,2037,...,0,0,16,11,1,2,0,66,66,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269995,6,0.640,1398,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
269996,6,0.577,1364,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
269997,6,0.666,1366,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
269998,6,0.687,1461,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5
269999,6,16.740,1374,80,7.0,4,224,0,3,180,...,0,0,6,1,0,2,2,62,60,5

In [28]:
x = test["NewLabel"].value_counts()
print(x)

0    45000
1    45000
2    45000
3    45000
4    45000
5    45000
Name: NewLabel, dtype: int64

In [29]:
test.to_csv('test.csv')

In [35]:
new_data.reset_index(inplace=True)
new_data = new_data.iloc[:,1:]
new_data

,protocol,duration,src_port,dst_port,ndpi_proto_num,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,...,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,NewLabel
0,6,0.120,52012,3389,88.0,3,217,43,2,139,...,2,0,4,2,0,2,0,66,66,0
1,6,1.239,9454,3389,88.0,9,1170,672,6,637,...,2,0,14,9,0,2,0,66,66,0
2,6,0.057,13910,3389,88.0,1,171,117,1,54,...,0,0,2,1,0,0,0,0,0,0
3,6,0.312,14708,3389,88.0,2,193,85,2,108,...,0,0,4,1,0,0,1,0,0,0
4,6,1.733,18056,3389,88.0,10,1225,673,8,745,...,2,0,17,9,0,2,1,66,66,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3763547,6,8.952,1231,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3763548,6,8.964,1229,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3763549,6,8.894,1227,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3763550,6,8.983,1245,443,91.0,3,186,0,0,0,...,0,0,0,0,0,3,0,62,0,5
3763551,6,0.709,1539,80,7.0,9,1334,840,12,12991,...,0,0,20,5,0,2,2,62,62,5

In [39]:
new_data.to_csv('trainn.csv')